services:
  kroki:
    image: yuzutech/kroki:latest
    container_name: quiz_renderer2
    environment:
      - KROKI_SAFE_MODE=unsafe
    ports:
      - "8001:8000"
    restart: always

  bot:
    build: .
    container_name: quiz_bot2
    depends_on:
      - kroki
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./questions:/app/questions
    restart: always