services:
  kroki:
    image: yuzutech/kroki:latest
    container_name: quiz_renderer2
    environment:
      - KROKI_SAFE_MODE=unsafe
    ports:
      - "8001:8000"  # Swapped host port to 8001 to prevent port conflicts
    restart: always

  bot:
    build: .
    container_name: quiz_bot2
    depends_on:
      - kroki
    stdin_open: true
    tty: true
    environment:
      - KROKI_URL=http://kroki:8000
    volumes:
      - ./logs:/app/logs
      - ./questions:/app/questions
      - ./config.json:/app/config.json
    restart: always